-- Pedido do usuario: "para criar os itens e as ferramentas precisam ser
-- dropadas" -- medido: 236 dos 249 materiais do catalogo (depois do fix em
-- schema_catalogo_materiais_completo.sql) nao tinham NENHUM monstro
-- dropando algo com nome parecido -- ou seja, a maioria dos materiais que
-- as 16 profissoes pedem nas receitas so eram alcancaveis (quando eram) via
-- missao, nunca por combate direto.
--
-- Distribuicao automatica: cada material sem cobertura foi atribuido a 1
-- monstro cujo nivel_recomendado bate com a faixa esperada pra raridade
-- dele (comum->nivel 1-3, incomum->3-5, raro->5-7, epico->7-9,
-- lendario->9-11), com leve preferencia tematica (material "animal" prefere
-- monstro-bicho, "vegetal" prefere monstro-planta, "mineral" prefere
-- construto/labirinto) quando da pra inferir do proprio id do monstro, e
-- balanceado pra nao empilhar tudo nos mesmos poucos monstros. Chance por
-- raridade: comum 50% / incomum 30% / raro 15% / epico 7% / lendario 3%.
--
-- Bug corrigido no meio do caminho: nivel_recomendado tem texto tipo
-- "1-3 (andar 2)" -- o "(andar 2)" e o PISO de Aincrad, nao dificuldade;
-- contar esse numero junto no calculo de nivel medio distorcia a
-- classificacao (achado no boss de raid baran_o_rei_touro, que teria virado
-- "nivel 2" e ganho material comum em vez de lendario).
--
-- ENTRADAS ACRESCENTADAS aos drops existentes de cada monstro (nao
-- substitui o que ja tinha -- so soma no array).

update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Agulha Magnetizada", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}, {"item": "Linha Resistente", "chance": "30%", "qtd": "1-2", "serve": "Craft (tecido)", "raridade": "Incomum"}]'::jsonb where id = 'abelha_gigante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Açúcar Raro", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}, {"item": "Carne De Monstro Raro", "chance": "15%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Raro"}, {"item": "Couro Sombrio", "chance": "15%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Raro"}, {"item": "Frasco Especial", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}, {"item": "Presa De Monstro", "chance": "15%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Raro"}]'::jsonb where id = 'aguia_de_pedra';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Açúcar Natural", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Corrente Simples", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Essência Flamejante", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Linha De Aço", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Pena De Ave Grande", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Seda Crua (fios)", "chance": "50%", "qtd": "1-3", "serve": "Craft (tecido)", "raridade": "Comum"}]'::jsonb where id = 'aguia_do_planalto';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carne De Chefe", "chance": "7%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Epico"}, {"item": "Cristal De Controle", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Cristal Flamejante", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Essência Elemental", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Manta Térmica (peça)", "chance": "7%", "qtd": "1", "serve": "Craft (tecido)", "raridade": "Epico"}, {"item": "Núcleo De Monstro Chefe", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Ouro Folha (24k)", "chance": "7%", "qtd": "1", "serve": "Craft (nobre)", "raridade": "Epico"}]'::jsonb where id = 'alfa_lupino';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Bandagem Purificada", "chance": "30%", "qtd": "1-2", "serve": "Craft (quimico)", "raridade": "Incomum"}, {"item": "Molde Gravado", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}]'::jsonb where id = 'aranha_de_luz_velada';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cabeca Balanceada", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}, {"item": "Óleo Animal (banha)", "chance": "30%", "qtd": "1-2", "serve": "Craft (animal)", "raridade": "Incomum"}]'::jsonb where id = 'aranha_sombria';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carne Lendaria", "chance": "7%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Epico"}, {"item": "Cristal De Forca", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Cristal Sombrio", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Essência Espiritual", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Metal Lendario", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Núcleo de Dragão Bebê", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Tempero Lendario", "chance": "7%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Epico"}]'::jsonb where id = 'arauto_das_alturas';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Aço Incomum (lingote)", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Corrente De Aço", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Essência Espacial", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Ferro Reforcado", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Flechas Perfurantes", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Lâmina de Prata (1mm)", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}]'::jsonb where id = 'armadura_animada';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Fragmento de Aincrad", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Cristal Azul Perfeito", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Erva Lendaria", "chance": "3%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Lendario"}, {"item": "Essência Do Sistema", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Frutas Lendarias", "chance": "3%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Lendario"}, {"item": "Núcleo Ancestral", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Runa de Vida (cópia)", "chance": "3%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Lendario"}]'::jsonb where id = 'baran_o_rei_touro';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Corda Encantada", "chance": "30%", "qtd": "1-2", "serve": "Craft (tecido)", "raridade": "Incomum"}, {"item": "Madeira Nodosa", "chance": "30%", "qtd": "1-2", "serve": "Craft (vegetal)", "raridade": "Incomum"}]'::jsonb where id = 'centopeia_do_aqueduto';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Água Limpa", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Couro De Lobo", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Essência Lunar", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Linha Mistica", "chance": "50%", "qtd": "1-3", "serve": "Craft (tecido)", "raridade": "Comum"}, {"item": "Pena Pequena", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Seda Resistente", "chance": "50%", "qtd": "1-3", "serve": "Craft (tecido)", "raridade": "Comum"}]'::jsonb where id = 'coruja_das_sombras';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Água Pura", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Couro Fino", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Ferro", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Linha Reforcada", "chance": "50%", "qtd": "1-3", "serve": "Craft (tecido)", "raridade": "Comum"}, {"item": "Pena Rara", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Tecido Resistente", "chance": "50%", "qtd": "1-3", "serve": "Craft (tecido)", "raridade": "Comum"}]'::jsonb where id = 'corvo_das_ruinas';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Casca de Árvore Anciã", "chance": "7%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Epico"}, {"item": "Cristal De Vento", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Cristal Vital", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Ervas Ancestrais", "chance": "7%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Epico"}, {"item": "Néctar de Flor Lunar", "chance": "7%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Epico"}, {"item": "Núcleo de Prata", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}]'::jsonb where id = 'ent_anciao';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Couro Cru", "chance": "30%", "qtd": "1-2", "serve": "Craft (animal)", "raridade": "Incomum"}, {"item": "Osso De Chefe", "chance": "30%", "qtd": "1-2", "serve": "Craft (animal)", "raridade": "Incomum"}]'::jsonb where id = 'enxame_de_abelhas_douradas';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Couro Curtido", "chance": "30%", "qtd": "1-2", "serve": "Craft (animal)", "raridade": "Incomum"}, {"item": "Osso De Fera", "chance": "30%", "qtd": "1-2", "serve": "Craft (animal)", "raridade": "Incomum"}]'::jsonb where id = 'enxame_do_rio';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Couro Nobre", "chance": "30%", "qtd": "1-2", "serve": "Craft (animal)", "raridade": "Incomum"}, {"item": "Pergaminho Simples", "chance": "30%", "qtd": "1-2", "serve": "Craft (quimico)", "raridade": "Incomum"}]'::jsonb where id = 'escorpiao_de_poeira';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Água Cristalizada", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}, {"item": "Cristal De Defesa", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Essência Magica", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Frasco Reforcado", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}, {"item": "Seda Rara", "chance": "15%", "qtd": "1", "serve": "Craft (tecido)", "raridade": "Raro"}]'::jsonb where id = 'espectro_sussurrante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cristal Azul", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}, {"item": "Pinca De Precisao", "chance": "30%", "qtd": "1-2", "serve": "Craft (quimico)", "raridade": "Incomum"}]'::jsonb where id = 'fada_da_poeira';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Água Purificada", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Cristal De Deteccao", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Ferro Bruto (sucata)", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Fibra de Linho", "chance": "50%", "qtd": "1-3", "serve": "Craft (tecido)", "raridade": "Comum"}, {"item": "Placa De Ferro", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Tempero Natural", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}]'::jsonb where id = 'frenzy_boar';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Couro Reforcado", "chance": "30%", "qtd": "1-2", "serve": "Craft (animal)", "raridade": "Incomum"}, {"item": "Tecido Grosso", "chance": "30%", "qtd": "1-2", "serve": "Craft (tecido)", "raridade": "Incomum"}]'::jsonb where id = 'gafanhoto_gigante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Barra De Aço", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Cristal De Fogo", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Essência Mistica", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Flecha Perfeita", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Ouro Refinado", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Prata Refinada", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}]'::jsonb where id = 'guardiao_das_planicies';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Aço Raro (lingote)", "chance": "7%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Epico"}, {"item": "Cristal Elemental", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Escama De Dragao", "chance": "7%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Epico"}, {"item": "Flechas Perfeitas", "chance": "7%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Epico"}, {"item": "Núcleo De Criatura Ancestral", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Olho de Coruja Sombria", "chance": "7%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Epico"}]'::jsonb where id = 'guardiao_de_mournhall';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Favo Dourado Completo", "chance": "7%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Epico"}, {"item": "Cristal Elemental Supremo", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Essência Divina (gota)", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Gema Branca Lapidada", "chance": "7%", "qtd": "1", "serve": "Craft (nobre)", "raridade": "Epico"}, {"item": "Núcleo De Gigante", "chance": "7%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Epico"}, {"item": "Osso Lendário de Chefe", "chance": "7%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Epico"}]'::jsonb where id = 'guerreiro_kobold';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cristal Claro", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}, {"item": "Tinta Preta", "chance": "30%", "qtd": "1-2", "serve": "Craft (quimico)", "raridade": "Incomum"}]'::jsonb where id = 'hound_de_cobre';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Fragmento de Adamantita", "chance": "3%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Lendario"}, {"item": "Cristal Espiritual", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Essência Ancestral", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Essência Lendaria", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Gema do Andar 10", "chance": "3%", "qtd": "1", "serve": "Craft (nobre)", "raridade": "Lendario"}, {"item": "Liga De Mithril", "chance": "3%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Lendario"}]'::jsonb where id = 'illfang_the_kobold_lord';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cristal Luminoso", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}]'::jsonb where id = 'lacustre_vagador';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Água Sagrada", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Cristal De Fogo Pequeno", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Fivela De Ferro", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Minério De Bronze", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Placa De Ferro Pequena", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Tempero Simples", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}]'::jsonb where id = 'lagarto_da_floresta';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Argila Bruta", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Cristal De Impacto", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Flechas Simples", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Óleo", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Placa Reforcada", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}]'::jsonb where id = 'libelula_cortante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Barra De Bronze", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Cristal Natural", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Erva Aromatica", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Erva Curativa", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Erva Escura", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Erva Purificadora", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Ervas Tranquilas", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Fibra Forte", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Frutas Raras", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Madeira Comum", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Madeira Leve", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Madeira Resistente", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Resina Natural", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}]'::jsonb where id = 'little_nepenthes';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Encadernação Reforcada", "chance": "30%", "qtd": "1-2", "serve": "Craft (tecido)", "raridade": "Incomum"}]'::jsonb where id = 'lobo_da_alcateia';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cera de Carnaúba", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Cristal De Furtividade", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Erva Ancestral", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Ervas Especiais", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Fruta Rara", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Raiz Gigante", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}]'::jsonb where id = 'mae_raiz_de_horunka';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cogumelo Especial", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Cristal De Localizacao", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Essência Oculta", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Molho Raro", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}, {"item": "Tempero Especial", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}]'::jsonb where id = 'mimic_de_marcos';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Barra De Ferro", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Cristal Verde", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Frasco", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Óleo Natural", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Pó Mineral", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}]'::jsonb where id = 'morcego_ecoante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carne De Animal", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Cristal Vermelho", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Frasco Vazio", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Pedra Comum", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Ponta De Aço", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}]'::jsonb where id = 'mosca_venenosa';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Coral Negro (pedaço)", "chance": "15%", "qtd": "1", "serve": "Craft (nobre)", "raridade": "Raro"}, {"item": "Cristal De Precisao", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Essência Protetora", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Núcleo De Monstro", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Veneno Natural", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}]'::jsonb where id = 'porta_estandarte_de_illfang';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Forja Compacta", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}]'::jsonb where id = 'predador_de_vaelor';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Fragmento Dimensional", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}]'::jsonb where id = 'ra_venenosa_gigante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carne De Monstro", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Erva Medicinal Comum", "chance": "50%", "qtd": "1-3", "serve": "Craft (quimico)", "raridade": "Comum"}, {"item": "Garra De Fera", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Pedra De Amolar", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Ponta De Ferro", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}]'::jsonb where id = 'rato_gigante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cristais Puros", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Cristal Prismatico", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Essência Da Vida", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}, {"item": "Fio de Destino (1 metro)", "chance": "3%", "qtd": "1", "serve": "Craft (tecido)", "raridade": "Lendario"}, {"item": "Ingrediente Unico", "chance": "3%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Lendario"}, {"item": "Núcleo De Guardiao", "chance": "3%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Lendario"}]'::jsonb where id = 'rei_das_planicies';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carvao", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Fio de Alumínio", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Lâmina Fina Polida", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Prata Bruta", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}]'::jsonb where id = 'ruin_kobold_arqueiro';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carvao Refinado", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Cristal De Retorno", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Erva Curativa Rara", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Ervas Selvagens", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Placa De Aço", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}, {"item": "Vidro Temperado", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}]'::jsonb where id = 'ruin_kobold_sentinel';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Pepita de Cobre", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Fio Prata", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Lâmina Temperada", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Serpentina De Cobre", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}]'::jsonb where id = 'ruin_kobold_trooper';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Fragmento Magico", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}]'::jsonb where id = 'sanguessuga_gigante';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Corda Forte", "chance": "15%", "qtd": "1", "serve": "Craft (tecido)", "raridade": "Raro"}, {"item": "Cristal De Visao", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Erva Forte", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Ervas Sombras", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Planta Veloz", "chance": "15%", "qtd": "1", "serve": "Craft (vegetal)", "raridade": "Raro"}, {"item": "Virote De Aço", "chance": "15%", "qtd": "1", "serve": "Craft (mineral)", "raridade": "Raro"}]'::jsonb where id = 'sentinela_esquecida';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Erva Vital", "chance": "30%", "qtd": "1-2", "serve": "Craft (vegetal)", "raridade": "Incomum"}, {"item": "Resina de Árvore", "chance": "30%", "qtd": "1-2", "serve": "Craft (vegetal)", "raridade": "Incomum"}]'::jsonb where id = 'serpente_das_aguas_rasas';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Lente Polida", "chance": "30%", "qtd": "1-2", "serve": "Craft (quimico)", "raridade": "Incomum"}]'::jsonb where id = 'slime';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Cristal Branco (pequeno)", "chance": "15%", "qtd": "1", "serve": "Craft (nobre)", "raridade": "Raro"}, {"item": "Essência De Monstro", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Essência Vital", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}, {"item": "Peixe Raro", "chance": "15%", "qtd": "1", "serve": "Craft (exotico)", "raridade": "Raro"}]'::jsonb where id = 'sombra_de_mournhall';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carvão Mineral", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Essência Aquatica", "chance": "50%", "qtd": "1-3", "serve": "Craft (exotico)", "raridade": "Comum"}, {"item": "Latao Em Pó", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Pedra Lascada", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}, {"item": "Ponta De Ferro Afiada", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}]'::jsonb where id = 'stabbing_wasp';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Látex Bruto", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Erva Aquatica", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Erva Azul", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Erva Doce", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Erva Lubrificante", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Ervas Medicinais", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Farinha", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Fibra Vegetal", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Madeira de Pinho", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Madeira De Carvalho", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Madeira Nobre", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Palha Seca", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}, {"item": "Trigo", "chance": "50%", "qtd": "1-3", "serve": "Craft (vegetal)", "raridade": "Comum"}]'::jsonb where id = 'toca_na_raiz';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Corda", "chance": "50%", "qtd": "1-3", "serve": "Craft (tecido)", "raridade": "Comum"}, {"item": "Escama De Monstro", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Leite Fresco", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Pena De Ave", "chance": "50%", "qtd": "1-3", "serve": "Craft (animal)", "raridade": "Comum"}, {"item": "Rebite De Ferro", "chance": "50%", "qtd": "1-3", "serve": "Craft (mineral)", "raridade": "Comum"}]'::jsonb where id = 'touro_das_colinas';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Liga Resistente Ao Fogo", "chance": "30%", "qtd": "1-2", "serve": "Craft (exotico)", "raridade": "Incomum"}]'::jsonb where id = 'trepadeira_estranguladora';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Carne De Caca Rara", "chance": "15%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Raro"}, {"item": "Carne Resistente", "chance": "15%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Raro"}, {"item": "Fio de Seda Selvagem", "chance": "15%", "qtd": "1", "serve": "Craft (tecido)", "raridade": "Raro"}, {"item": "Pólvora", "chance": "15%", "qtd": "1", "serve": "Craft (quimico)", "raridade": "Raro"}, {"item": "Sangue De Monstro", "chance": "15%", "qtd": "1", "serve": "Craft (animal)", "raridade": "Raro"}]'::jsonb where id = 'urso_de_pedra';
update monstros set drops = coalesce(drops, '[]'::jsonb) || '[{"item": "Corrente Sagrada", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Gatilho Afiado", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}, {"item": "Pó de Latão (esmeril)", "chance": "30%", "qtd": "1-2", "serve": "Craft (mineral)", "raridade": "Incomum"}]'::jsonb where id = 'verme_de_cristal';
