/* Metadados de cada tabela pro painel do mestre (admin.html) — nome da
   coluna, tipo de campo pro formulario, e qual e' a chave primaria. Espelha
   exatamente scripts/db/schema.sql; se mudar uma coluna la, muda aqui
   tambem. Tipos de campo: text | textarea | number | bool | json
   ("json" cobre jsonb e array — edita como texto JSON cru, validado antes
   de salvar). */

var TABELAS_ADMIN = {
  npcs: {
    pk: "id",
    rotulo: "NPCs",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "papel", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "arma", tipo: "text" },
      { nome: "local", tipo: "text" },
      { nome: "atributos", tipo: "json" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "gancho", tipo: "textarea" },
      { nome: "falas", tipo: "json" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "canonico", tipo: "bool" },
      { nome: "fonte", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  monstros: {
    pk: "id",
    rotulo: "Monstros",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "epiteto", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "carta", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "zona", tipo: "text" },
      { nome: "regioes", tipo: "json" },
      { nome: "nivel_recomendado", tipo: "text" },
      { nome: "ameaca", tipo: "text" },
      { nome: "golpes", tipo: "text" },
      { nome: "local", tipo: "text" },
      { nome: "canonico", tipo: "bool" },
      { nome: "fonte", tipo: "text" },
      { nome: "fraqueza", tipo: "text" },
      { nome: "atributo_fraqueza", tipo: "text" },
      { nome: "fraquezas", tipo: "json" },
      { nome: "resistencias", tipo: "json" },
      { nome: "vulnerabilidades", tipo: "json" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "habitat", tipo: "textarea" },
      { nome: "comportamento", tipo: "textarea" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "sinal", tipo: "textarea" },
      { nome: "lore", tipo: "textarea" },
      { nome: "notas", tipo: "textarea", segredo: true },
      { nome: "drops", tipo: "json" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  armas: {
    pk: "id",
    rotulo: "Armas (itens)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "requisito", tipo: "text" },
      { nome: "preco", tipo: "number" },
      { nome: "preco_txt", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "efeito", tipo: "textarea" },
      { nome: "obter", tipo: "textarea" },
      { nome: "skills", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  equipamentos: {
    pk: "id",
    rotulo: "Equipamentos",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "slot", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "conjunto", tipo: "bool" },
      { nome: "arquivo", tipo: "text" },
      { nome: "requisito", tipo: "text" },
      { nome: "preco", tipo: "number" },
      { nome: "preco_txt", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "efeito", tipo: "textarea" },
      { nome: "obter", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  moves_arma: {
    pk: "nome",
    rotulo: "Moves de Arma",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "marca", tipo: "textarea" },
      { nome: "move_a", tipo: "json" },
      { nome: "move_b", tipo: "json" },
      { nome: "golpe_2", tipo: "json" },
      { nome: "golpe_3", tipo: "json" },
      { nome: "limit_breaker", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  moves_profissao: {
    pk: "nome",
    rotulo: "Moves de Profissão",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "marca", tipo: "textarea" },
      { nome: "move_a", tipo: "json" },
      { nome: "move_b", tipo: "json" },
      { nome: "move_c", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  sistema: {
    pk: "titulo",
    rotulo: "Regras (Sistema)",
    campos: [
      { nome: "titulo", tipo: "text" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  mercado: {
    pk: "id",
    rotulo: "Mercado (lojas)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "desconto", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  compra_materiais: {
    pk: "id",
    rotulo: "Compra de Materiais",
    semVisivel: false,
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "material", tipo: "text" },
      { nome: "col", tipo: "text" },
      { nome: "quem", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  quests: {
    pk: "id",
    rotulo: "Quests",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "titulo", tipo: "text" },
      { nome: "cadeia", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "dificuldade", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "npc", tipo: "text" },
      { nome: "requer", tipo: "json" },
      { nome: "desbloqueia", tipo: "json" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cronicas: {
    pk: "id",
    rotulo: "Crônicas",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "numero", tipo: "number" },
      { nome: "ep_rotulo", tipo: "text" },
      { nome: "titulo", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "dificuldade", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "conexoes", tipo: "text" },
      { nome: "elenco", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  guias: {
    pk: "id",
    rotulo: "Guias de Região",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "bioma", tipo: "text" },
      { nome: "nivel", tipo: "text" },
      { nome: "chegada", tipo: "text" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "cena", tipo: "textarea" },
      { nome: "acoes", tipo: "json" },
      { nome: "mestre", tipo: "textarea", segredo: true },
      { nome: "demora", tipo: "textarea" },
      { nome: "evento", tipo: "textarea" },
      { nome: "locais", tipo: "json" },
      { nome: "ligado", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  puzzles: {
    pk: "id",
    rotulo: "Puzzles",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "n", tipo: "number" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "cadeia", tipo: "text" },
      { nome: "duracao", tipo: "text" },
      { nome: "verdade", tipo: "textarea", segredo: true },
      { nome: "recompensa", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  oficios: {
    pk: "nome",
    rotulo: "Ofícios",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "marca", tipo: "textarea" },
      { nome: "acoes", tipo: "json" },
      { nome: "postos", tipo: "json" },
      { nome: "contato", tipo: "text" },
      { nome: "gancho", tipo: "textarea" },
      { nome: "renda", tipo: "text" },
      { nome: "item", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  dungeons: {
    pk: "id",
    rotulo: "Dungeons",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "nivel", tipo: "text" },
      { nome: "perfil", tipo: "textarea" },
      { nome: "nota", tipo: "textarea" },
      { nome: "setores", tipo: "json" },
      { nome: "salas", tipo: "json" },
      { nome: "ligacoes", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  salas_dungeon: {
    pk: "id",
    rotulo: "Salas de Dungeon",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "dungeon_id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  producao: {
    pk: "profissao",
    rotulo: "Produção (crafting)",
    campos: [
      { nome: "profissao", tipo: "text" },
      { nome: "moeda", tipo: "text" },
      { nome: "itens", tipo: "json" },
      { nome: "vale", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  pontos: {
    pk: "id",
    rotulo: "Pontos do Mapa",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "categoria", tipo: "text" },
      { nome: "x", tipo: "number" },
      { nome: "y", tipo: "number" },
      { nome: "tipo", tipo: "text" },
      { nome: "ref", tipo: "text" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "respawn_horas", tipo: "number" },
      { nome: "teste", tipo: "json" },
      { nome: "recompensa", tipo: "textarea" },
      { nome: "ameaca", tipo: "text" },
      { nome: "golpes", tipo: "text" },
      { nome: "atributo_fraqueza", tipo: "text" },
      { nome: "fala", tipo: "textarea" },
      { nome: "oferece", tipo: "text" },
      { nome: "vende", tipo: "text" },
      { nome: "obs", tipo: "textarea" },
      { nome: "mestre", tipo: "textarea", segredo: true },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  pontos_detalhe: {
    pk: "id",
    rotulo: "Pontos — Detalhe",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "oque", tipo: "textarea" },
      { nome: "acoes", tipo: "json" },
      { nome: "mestre", tipo: "textarea", segredo: true },
      { nome: "atalhos", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  clas: {
    pk: "nome",
    rotulo: "Clãs",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "destaque", tipo: "bool" },
      { nome: "forca", tipo: "text" },
      { nome: "necessidade", tipo: "text" },
      { nome: "rival", tipo: "text" },
      { nome: "rumor", tipo: "text" },
      { nome: "status", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "bons", tipo: "textarea" },
      { nome: "precisa", tipo: "textarea" },
      { nome: "nao_admitem", tipo: "textarea" },
      { nome: "proximo", tipo: "textarea" },
      { nome: "atravessado", tipo: "textarea" },
      { nome: "quests", tipo: "textarea" },
      { nome: "aparecem", tipo: "textarea" },
      { nome: "simbolo", tipo: "textarea" },
      { nome: "reputacao", tipo: "json" },
      { nome: "ganchos", tipo: "json", segredo: true },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  personagens: {
    pk: "nome",
    rotulo: "Personagens (jogadores)",
    campos: [
      { nome: "dono_id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "guilda", tipo: "text" },
      { nome: "arma", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "conceito", tipo: "textarea" },
      { nome: "referencias", tipo: "text" },
      { nome: "aparencia", tipo: "textarea" },
      { nome: "atributos", tipo: "json" },
      { nome: "arma_detalhe", tipo: "json" },
      { nome: "profissao_detalhe", tipo: "json" },
      { nome: "companheiro", tipo: "json" },
      { nome: "estado", tipo: "json" },
      { nome: "simbolo", tipo: "textarea" },
      { nome: "col_mao", tipo: "number" },
      { nome: "col_guardado", tipo: "number" },
      { nome: "col_ganho_hoje", tipo: "number" },
      { nome: "col_reset_dia", tipo: "text" },
      { nome: "folego", tipo: "number" },
      { nome: "folego_atualizado_em", tipo: "text" },
      { nome: "bug", tipo: "number" },
      { nome: "bug_ate", tipo: "text" },
      { nome: "carga_limit", tipo: "number" },
      { nome: "equipado", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  documentos: {
    pk: "id",
    rotulo: "Documentos (RAG)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "caminho", tipo: "text" },
      { nome: "titulo", tipo: "text" },
      { nome: "categoria", tipo: "text" },
      { nome: "publico", tipo: "bool" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cidades: {
    pk: "id",
    rotulo: "Cidades",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "andar", tipo: "text" },
      { nome: "tipo_de_zona", tipo: "text" },
      { nome: "guildas_presentes", tipo: "json" },
      { nome: "canonico", tipo: "bool" },
      { nome: "fonte", tipo: "text" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "arquivo", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cartas: {
    pk: "id",
    rotulo: "Cartas (catálogo)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "tipo_bonus", tipo: "text" },
      { nome: "valor_bonus", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "drop_de", tipo: "text" },
      { nome: "chance_drop", tipo: "number" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cristais: {
    pk: "id",
    rotulo: "Cristais (catálogo)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "tipo_bonus", tipo: "text" },
      { nome: "valor_bonus", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "drop_de", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  inventario: {
    pk: "id",
    rotulo: "Inventário",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "item_id", tipo: "text" },
      { nome: "quantidade", tipo: "number" },
      { nome: "equipado", tipo: "bool" },
      { nome: "slot", tipo: "text" },
      { nome: "cristal_id", tipo: "text" },
      { nome: "origem", tipo: "text" },
      { nome: "obtido_em", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
    ],
  },
  ferramentas_oficio: {
    pk: "id",
    rotulo: "Ferramentas de Ofício (catálogo)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "nivel_ferramenta", tipo: "number" },
      { nome: "bonus_acao", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "receita", tipo: "json" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  personagem_ferramentas: {
    pk: "personagem_nome",
    rotulo: "Personagem → Ferramentas",
    campos: [
      { nome: "personagem_nome", tipo: "text" },
      { nome: "ferramenta_id", tipo: "text" },
      { nome: "nivel_atual", tipo: "number" },
      { nome: "obtido_em", tipo: "text" },
    ],
  },
  criaturas_domadas: {
    pk: "id",
    rotulo: "Pets / Criaturas Domadas",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "especie", tipo: "text" },
      { nome: "nome_pet", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "status", tipo: "text" },
      { nome: "choca_em", tipo: "text" },
      { nome: "efeitos", tipo: "json" },
      { nome: "nascido_em", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
    ],
  },
  nivel_profissao: {
    pk: "personagem_nome",
    rotulo: "Nível de Profissão",
    campos: [
      { nome: "personagem_nome", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "nivel", tipo: "number" },
      { nome: "xp", tipo: "number" },
      { nome: "ultima_acao", tipo: "text" },
    ],
  },
  transacoes: {
    pk: "id",
    rotulo: "Transações (Col)",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "de_personagem", tipo: "text" },
      { nome: "para_personagem", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "valor", tipo: "number" },
      { nome: "item_id", tipo: "text" },
      { nome: "observacao", tipo: "text" },
      { nome: "criado_em", tipo: "text" },
    ],
  },
  vitrine: {
    pk: "id",
    rotulo: "Vitrine (Mercado Jogador)",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "vendedor_nome", tipo: "text" },
      { nome: "inventario_id", tipo: "number" },
      { nome: "preco_col", tipo: "number" },
      { nome: "criado_em", tipo: "text" },
      { nome: "expira_em", tipo: "text" },
      { nome: "vendido", tipo: "bool" },
      { nome: "comprador_nome", tipo: "text" },
      { nome: "vendido_em", tipo: "text" },
    ],
  },
  nivel_profissao_xp: {
    pk: "nivel",
    rotulo: "Curva XP de Profissão (catálogo)",
    campos: [
      { nome: "nivel", tipo: "number" },
      { nome: "xp_necessario", tipo: "number" },
    ],
  },
  missoes_quadro: {
    pk: "id",
    rotulo: "Missões (Quadro - catálogo)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "titulo", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "regiao", tipo: "text" },
      { nome: "alvo", tipo: "text" },
      { nome: "alvo_qtd", tipo: "number" },
      { nome: "raridade", tipo: "text" },
      { nome: "custo_folego", tipo: "number" },
      { nome: "recompensa_xp", tipo: "number" },
      { nome: "recompensa_col_min", tipo: "number" },
      { nome: "recompensa_col_max", tipo: "number" },
      { nome: "drop_item_id", tipo: "text" },
      { nome: "drop_chance", tipo: "number" },
      { nome: "drop_tabela", tipo: "text" },
      { nome: "reputacao_cla_nome", tipo: "text" },
      { nome: "reputacao_delta", tipo: "number" },
      { nome: "penalidade_col_falha", tipo: "number" },
      { nome: "penalidade_folego_falha", tipo: "number" },
      { nome: "nivel_min", tipo: "number" },
      { nome: "requer_grupo", tipo: "bool" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
      { nome: "updated_at", tipo: "text" },
    ],
  },
  missao_diaria: {
    pk: "id",
    rotulo: "Missões Diárias (por personagem)",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "missao_id", tipo: "text" },
      { nome: "status", tipo: "text" },
      { nome: "oferecida_em", tipo: "text" },
      { nome: "aceita_em", tipo: "text" },
      { nome: "concluida_em", tipo: "text" },
      { nome: "resultado", tipo: "json" },
    ],
  },
  craft_fila: {
    pk: "id",
    rotulo: "Fila de Crafting",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "receita_id", tipo: "text" },
      { nome: "quantidade", tipo: "number" },
      { nome: "iniciado_em", tipo: "text" },
      { nome: "pronto_em", tipo: "text" },
      { nome: "status", tipo: "text" },
      { nome: "resultado", tipo: "json" },
    ],
  },
  reputacao_personagem: {
    pk: "personagem_nome",
    rotulo: "Reputação (por clã)",
    campos: [
      { nome: "personagem_nome", tipo: "text" },
      { nome: "cla_nome", tipo: "text" },
      { nome: "nivel", tipo: "number" },
      { nome: "ultima_alteracao", tipo: "text" },
      { nome: "motivo", tipo: "text" },
    ],
  },
  mercado_itens: {
    pk: "id",
    rotulo: "Mercado NPC → Itens à venda",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "mercado_id", tipo: "text" },
      { nome: "item", tipo: "text" },
      { nome: "col", tipo: "text" },
      { nome: "obs", tipo: "text" },
    ],
  },
  perfis: {
    pk: "id",
    rotulo: "🔐 Perfis de Usuário (Auth)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "papel", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "criado_em", tipo: "text" },
    ],
  },
  conteudo_liberado: {
    pk: "id",
    rotulo: "Conteúdo liberado por jogador",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "jogador_id", tipo: "text" },
      { nome: "tabela", tipo: "text" },
      { nome: "registro_id", tipo: "text" },
      { nome: "liberado_em", tipo: "text" },
    ],
  },
  documento_chunks: {
    pk: "id",
    rotulo: "RAG — Chunks de documento (embeddings)",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "documento_id", tipo: "text" },
      { nome: "ordem", tipo: "number" },
      { nome: "titulo_secao", tipo: "text" },
      { nome: "conteudo", tipo: "textarea" },
      { nome: "embedding", tipo: "json" },
      { nome: "created_at", tipo: "text" },
    ],
  },
  materiais_basicos: {
    pk: "id",
    rotulo: "🏭 Materiais Básicos de Craft (48)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "nivel_obtencao", tipo: "number" },
      { nome: "categoria", tipo: "text" },
      { nome: "peso_uso_esperado", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "fonte", tipo: "textarea" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
      { nome: "updated_at", tipo: "text" },
    ],
  },
  receitas: {
    pk: "id",
    rotulo: "📜 Receitas de Craft (128 = 16 prof × 8)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "nivel_receita", tipo: "number" },
      { nome: "tipo", tipo: "text" },
      { nome: "nome_resultado", tipo: "text" },
      { nome: "resultado_item_id", tipo: "text" },
      { nome: "resultado_raridade", tipo: "text" },
      { nome: "atributo_teste", tipo: "text" },
      { nome: "dificuldade_mod", tipo: "number" },
      { nome: "folego_custo", tipo: "number" },
      { nome: "xp_recompensa", tipo: "number" },
      { nome: "materiais", tipo: "json" },
      { nome: "efeitos", tipo: "json" },
      { nome: "receita_refino", tipo: "bool" },
      { nome: "receita_estagio", tipo: "number" },
      { nome: "receita_antecessora_id", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
      { nome: "updated_at", tipo: "text" },
    ],
  },
  ovos_catalogo: {
    pk: "id",
    rotulo: "🥚 Catálogo de Ovos (Pets)",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "especie", tipo: "text" },
      { nome: "monstro_id", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "nivel_min", tipo: "number" },
      { nome: "tempo_chocagem_horas", tipo: "number" },
      { nome: "incubadora_min", tipo: "number" },
      { nome: "efeitos_padrao", tipo: "json" },
      { nome: "como_obter", tipo: "textarea" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
      { nome: "updated_at", tipo: "text" },
    ],
  },
  criaturas_domadas: {
    pk: "id",
    rotulo: "🐾 Pets / Criaturas Domadas",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "especie", tipo: "text" },
      { nome: "monstro_id", tipo: "text" },
      { nome: "nome_pet", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "status", tipo: "text" },
      { nome: "incubadora_nivel", tipo: "number" },
      { nome: "efeitos", tipo: "json" },
      { nome: "choca_em", tipo: "text" },
      { nome: "nascido_em", tipo: "text" },
      { nome: "obtido_em", tipo: "text" },
      { nome: "updated_at", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
    ],
  },
  personagem_ferramentas: {
    pk: "personagem_nome",
    rotulo: "🧰 Personagem → Ferramentas de Ofício",
    campos: [
      { nome: "personagem_nome", tipo: "text" },
      { nome: "ferramenta_id", tipo: "text" },
      { nome: "obtido_em", tipo: "text" },
      { nome: "updated_at", tipo: "text" },
    ],
  },
  nivel_profissao: {
    pk: "personagem_nome",
    rotulo: "📈 Nível de Profissão (por jogador)",
    campos: [
      { nome: "personagem_nome", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "nivel", tipo: "number" },
      { nome: "xp", tipo: "number" },
      { nome: "ultima_acao", tipo: "text" },
      { nome: "updated_at", tipo: "text" },
    ],
  },
};
