/* Metadados de cada tabela pro painel do mestre (admin.html) — nome da
   coluna, tipo de campo pro formulario, e qual e' a chave primaria. Espelha
   exatamente scripts/db/schema.sql; se mudar uma coluna la, muda aqui
   tambem. Tipos de campo: text | textarea | number | bool | json
   ("json" cobre jsonb e array — edita como texto JSON cru, validado antes
   de salvar). */

var TABELAS_ADMIN = {
  npcs: { pk: "id", rotulo: "NPCs", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "arquivo", tipo: "text" }, { nome: "img", tipo: "text" },
    { nome: "papel", tipo: "text" }, { nome: "profissao", tipo: "text" },
    { nome: "arma", tipo: "text" }, { nome: "local", tipo: "text" },
    { nome: "atributos", tipo: "json" }, { nome: "resumo", tipo: "textarea" },
    { nome: "gancho", tipo: "textarea" }, { nome: "falas", tipo: "json" },
    { nome: "corpo", tipo: "textarea" }, { nome: "canonico", tipo: "bool" },
    { nome: "fonte", tipo: "text" }, { nome: "visivel", tipo: "bool" },
  ]},
  monstros: { pk: "id", rotulo: "Monstros", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "epiteto", tipo: "text" }, { nome: "arquivo", tipo: "text" },
    { nome: "img", tipo: "text" }, { nome: "carta", tipo: "text" },
    { nome: "tipo", tipo: "text" }, { nome: "zona", tipo: "text" },
    { nome: "regioes", tipo: "json" }, { nome: "nivel_recomendado", tipo: "text" },
    { nome: "ameaca", tipo: "text" }, { nome: "golpes", tipo: "text" },
    { nome: "local", tipo: "text" }, { nome: "canonico", tipo: "bool" },
    { nome: "fonte", tipo: "text" }, { nome: "fraqueza", tipo: "text" },
    { nome: "elemento_fraqueza", tipo: "text" }, { nome: "elemento_resistencia", tipo: "text" },
    { nome: "fraquezas", tipo: "json" }, { nome: "resistencias", tipo: "json" },
    { nome: "vulnerabilidades", tipo: "json" }, { nome: "domavel", tipo: "text" },
    { nome: "doma_sucessos", tipo: "text" }, { nome: "doma_requisito", tipo: "text" },
    { nome: "resumo", tipo: "textarea" }, { nome: "habitat", tipo: "textarea" },
    { nome: "comportamento", tipo: "textarea" }, { nome: "leitura", tipo: "textarea" },
    { nome: "sinal", tipo: "textarea" }, { nome: "lore", tipo: "textarea" },
    { nome: "notas", tipo: "textarea", segredo: true },
    { nome: "drops", tipo: "json" }, { nome: "corpo", tipo: "textarea" },
    { nome: "visivel", tipo: "bool" },
  ]},
  armas: { pk: "id", rotulo: "Armas (itens)", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "arquivo", tipo: "text" }, { nome: "img", tipo: "text" },
    { nome: "tipo", tipo: "text" }, { nome: "atributo", tipo: "text" },
    { nome: "raridade", tipo: "text" }, { nome: "requisito", tipo: "text" },
    { nome: "preco", tipo: "number" }, { nome: "preco_txt", tipo: "text" },
    { nome: "resumo", tipo: "textarea" }, { nome: "efeito", tipo: "textarea" },
    { nome: "obter", tipo: "textarea" }, { nome: "skills", tipo: "json" },
    { nome: "visivel", tipo: "bool" },
  ]},
  equipamentos: { pk: "id", rotulo: "Equipamentos", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "img", tipo: "text" }, { nome: "slot", tipo: "text" },
    { nome: "raridade", tipo: "text" }, { nome: "conjunto", tipo: "bool" },
    { nome: "arquivo", tipo: "text" }, { nome: "requisito", tipo: "text" },
    { nome: "preco", tipo: "number" }, { nome: "preco_txt", tipo: "text" },
    { nome: "resumo", tipo: "textarea" }, { nome: "efeito", tipo: "textarea" },
    { nome: "obter", tipo: "textarea" }, { nome: "visivel", tipo: "bool" },
  ]},
  moves_arma: { pk: "nome", rotulo: "Moves de Arma", campos: [
    { nome: "nome", tipo: "text" }, { nome: "atributo", tipo: "text" },
    { nome: "marca", tipo: "textarea" }, { nome: "move_a", tipo: "json" },
    { nome: "move_b", tipo: "json" }, { nome: "visivel", tipo: "bool" },
  ]},
  moves_profissao: { pk: "nome", rotulo: "Moves de Profissão", campos: [
    { nome: "nome", tipo: "text" }, { nome: "atributo", tipo: "text" },
    { nome: "marca", tipo: "textarea" }, { nome: "move_a", tipo: "json" },
    { nome: "move_b", tipo: "json" }, { nome: "visivel", tipo: "bool" },
  ]},
  sistema: { pk: "titulo", rotulo: "Regras (Sistema)", campos: [
    { nome: "titulo", tipo: "text" }, { nome: "corpo", tipo: "textarea" },
    { nome: "visivel", tipo: "bool" },
  ]},
  mercado: { pk: "id", rotulo: "Mercado (lojas)", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "regiao", tipo: "text" }, { nome: "descricao", tipo: "textarea" },
    { nome: "desconto", tipo: "text" }, { nome: "visivel", tipo: "bool" },
  ]},
  compra_materiais: { pk: "id", rotulo: "Compra de Materiais", semVisivel: false, campos: [
    { nome: "id", tipo: "number", auto: true }, { nome: "material", tipo: "text" },
    { nome: "col", tipo: "text" }, { nome: "quem", tipo: "text" },
    { nome: "visivel", tipo: "bool" },
  ]},
  quests: { pk: "id", rotulo: "Quests", campos: [
    { nome: "id", tipo: "text" }, { nome: "titulo", tipo: "text" },
    { nome: "cadeia", tipo: "text" }, { nome: "tipo", tipo: "text" },
    { nome: "dificuldade", tipo: "text" }, { nome: "regiao", tipo: "text" },
    { nome: "npc", tipo: "text" }, { nome: "requer", tipo: "json" },
    { nome: "desbloqueia", tipo: "json" }, { nome: "resumo", tipo: "textarea" },
    { nome: "corpo", tipo: "textarea" }, { nome: "visivel", tipo: "bool" },
  ]},
  cronicas: { pk: "id", rotulo: "Crônicas", campos: [
    { nome: "id", tipo: "text" }, { nome: "numero", tipo: "number" },
    { nome: "ep_rotulo", tipo: "text" }, { nome: "titulo", tipo: "text" },
    { nome: "arquivo", tipo: "text" }, { nome: "tipo", tipo: "text" },
    { nome: "dificuldade", tipo: "text" }, { nome: "regiao", tipo: "text" },
    { nome: "conexoes", tipo: "text" }, { nome: "elenco", tipo: "text" },
    { nome: "resumo", tipo: "textarea" }, { nome: "corpo", tipo: "textarea" },
    { nome: "visivel", tipo: "bool" },
  ]},
  guias: { pk: "id", rotulo: "Guias de Região", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "arquivo", tipo: "text" }, { nome: "bioma", tipo: "text" },
    { nome: "nivel", tipo: "text" }, { nome: "chegada", tipo: "text" },
    { nome: "leitura", tipo: "textarea" }, { nome: "cena", tipo: "textarea" },
    { nome: "acoes", tipo: "json" },
    { nome: "mestre", tipo: "textarea", segredo: true },
    { nome: "demora", tipo: "textarea" }, { nome: "evento", tipo: "textarea" },
    { nome: "locais", tipo: "json" }, { nome: "ligado", tipo: "json" },
    { nome: "visivel", tipo: "bool" },
  ]},
  puzzles: { pk: "id", rotulo: "Puzzles", campos: [
    { nome: "id", tipo: "text" }, { nome: "n", tipo: "number" },
    { nome: "nome", tipo: "text" }, { nome: "arquivo", tipo: "text" },
    { nome: "regiao", tipo: "text" }, { nome: "tipo", tipo: "text" },
    { nome: "cadeia", tipo: "text" }, { nome: "duracao", tipo: "text" },
    { nome: "verdade", tipo: "textarea", segredo: true },
    { nome: "recompensa", tipo: "textarea" }, { nome: "corpo", tipo: "textarea" },
    { nome: "visivel", tipo: "bool" },
  ]},
  oficios: { pk: "nome", rotulo: "Ofícios", campos: [
    { nome: "nome", tipo: "text" }, { nome: "atributo", tipo: "text" },
    { nome: "arquivo", tipo: "text" }, { nome: "marca", tipo: "textarea" },
    { nome: "acoes", tipo: "json" }, { nome: "postos", tipo: "json" },
    { nome: "contato", tipo: "text" }, { nome: "gancho", tipo: "textarea" },
    { nome: "renda", tipo: "text" }, { nome: "item", tipo: "text" },
    { nome: "visivel", tipo: "bool" },
  ]},
  dungeons: { pk: "id", rotulo: "Dungeons", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "regiao", tipo: "text" }, { nome: "nivel", tipo: "text" },
    { nome: "perfil", tipo: "textarea" }, { nome: "nota", tipo: "textarea" },
    { nome: "setores", tipo: "json" }, { nome: "salas", tipo: "json" },
    { nome: "ligacoes", tipo: "json" }, { nome: "visivel", tipo: "bool" },
  ]},
  salas_dungeon: { pk: "id", rotulo: "Salas de Dungeon", campos: [
    { nome: "id", tipo: "text" }, { nome: "dungeon_id", tipo: "text" },
    { nome: "nome", tipo: "text" }, { nome: "tipo", tipo: "text" },
    { nome: "leitura", tipo: "textarea" }, { nome: "corpo", tipo: "textarea" },
    { nome: "visivel", tipo: "bool" },
  ]},
  producao: { pk: "profissao", rotulo: "Produção (crafting)", campos: [
    { nome: "profissao", tipo: "text" }, { nome: "moeda", tipo: "text" },
    { nome: "itens", tipo: "json" }, { nome: "vale", tipo: "textarea" },
    { nome: "visivel", tipo: "bool" },
  ]},
  pontos: { pk: "id", rotulo: "Pontos do Mapa", campos: [
    { nome: "id", tipo: "text" }, { nome: "regiao", tipo: "text" },
    { nome: "nome", tipo: "text" }, { nome: "categoria", tipo: "text" },
    { nome: "x", tipo: "number" }, { nome: "y", tipo: "number" },
    { nome: "tipo", tipo: "text" }, { nome: "ref", tipo: "text" },
    { nome: "descricao", tipo: "textarea" }, { nome: "respawn_horas", tipo: "number" },
    { nome: "teste", tipo: "json" }, { nome: "recompensa", tipo: "textarea" },
    { nome: "ameaca", tipo: "text" }, { nome: "golpes", tipo: "text" },
    { nome: "atributo_fraqueza", tipo: "text" }, { nome: "fala", tipo: "textarea" },
    { nome: "oferece", tipo: "text" }, { nome: "vende", tipo: "text" },
    { nome: "obs", tipo: "textarea" },
    { nome: "mestre", tipo: "textarea", segredo: true },
    { nome: "visivel", tipo: "bool" },
  ]},
  pontos_detalhe: { pk: "id", rotulo: "Pontos — Detalhe", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "regiao", tipo: "text" }, { nome: "arquivo", tipo: "text" },
    { nome: "leitura", tipo: "textarea" }, { nome: "oque", tipo: "textarea" },
    { nome: "acoes", tipo: "json" },
    { nome: "mestre", tipo: "textarea", segredo: true },
    { nome: "atalhos", tipo: "json" }, { nome: "visivel", tipo: "bool" },
  ]},
  clas: { pk: "nome", rotulo: "Clãs", campos: [
    { nome: "nome", tipo: "text" }, { nome: "destaque", tipo: "bool" },
    { nome: "forca", tipo: "text" }, { nome: "necessidade", tipo: "text" },
    { nome: "rival", tipo: "text" }, { nome: "rumor", tipo: "text" },
    { nome: "status", tipo: "text" }, { nome: "resumo", tipo: "textarea" },
    { nome: "bons", tipo: "textarea" }, { nome: "precisa", tipo: "textarea" },
    { nome: "nao_admitem", tipo: "textarea" }, { nome: "proximo", tipo: "textarea" },
    { nome: "atravessado", tipo: "textarea" }, { nome: "quests", tipo: "textarea" },
    { nome: "aparecem", tipo: "textarea" }, { nome: "simbolo", tipo: "textarea" },
    { nome: "reputacao", tipo: "json" },
    { nome: "ganchos", tipo: "json", segredo: true },
    { nome: "visivel", tipo: "bool" },
  ]},
  personagens: { pk: "nome", rotulo: "Personagens (jogadores)", campos: [
    { nome: "nome", tipo: "text" }, { nome: "guilda", tipo: "text" },
    { nome: "arma", tipo: "text" }, { nome: "profissao", tipo: "text" },
    { nome: "conceito", tipo: "textarea" }, { nome: "referencias", tipo: "text" },
    { nome: "aparencia", tipo: "textarea" }, { nome: "atributos", tipo: "json" },
    { nome: "arma_detalhe", tipo: "json" }, { nome: "profissao_detalhe", tipo: "json" },
    { nome: "companheiro", tipo: "json" }, { nome: "estado", tipo: "json" },
    { nome: "simbolo", tipo: "textarea" }, { nome: "visivel", tipo: "bool" },
  ]},
  cidades: { pk: "id", rotulo: "Cidades", campos: [
    { nome: "id", tipo: "text" }, { nome: "nome", tipo: "text" },
    { nome: "andar", tipo: "text" }, { nome: "tipo_de_zona", tipo: "text" },
    { nome: "guildas_presentes", tipo: "json" }, { nome: "canonico", tipo: "bool" },
    { nome: "fonte", tipo: "text" }, { nome: "corpo", tipo: "textarea" },
    { nome: "arquivo", tipo: "text" }, { nome: "visivel", tipo: "bool" },
  ]},
};
