/* Metadados de cada tabela do banco pro Compêndio do Mestre — nome da
   coluna, tipo de campo de formulário e qual é a chave primária.

   Espelha 1:1 scripts/web/admin_schema.js (fonte da verdade compartilhada
   com o painel legado admin.html). Se mudar uma coluna no banco, muda nos
   dois lugares. Tipos de campo: text | textarea | number | bool | json
   ("json" cobre jsonb e array — edita como texto JSON cru, validado antes
   de salvar).

   Campo extra "auto" = chave gerada pelo banco (bigserial), não editável
   na criação. Campo extra "segredo" = só o mestre vê o valor de verdade
   (a view pública devolve null pra jogador) — mostramos um aviso no form. */

export const TABELAS_ADMIN = {
  monstros: {
    pk: "id",
    rotulo: "Monstros",
    icone: "💀",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "epiteto", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "carta", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "zona", tipo: "text" },
      { nome: "regioes", tipo: "json" },
      { nome: "nivel_recomendado", tipo: "text" },
      { nome: "ameaca", tipo: "text" },
      { nome: "golpes", tipo: "text" },
      { nome: "local", tipo: "text" },
      { nome: "canonico", tipo: "bool" },
      { nome: "fonte", tipo: "text" },
      { nome: "fraqueza", tipo: "text" },
      { nome: "atributo_fraqueza", tipo: "text" },
      { nome: "fraquezas", tipo: "json" },
      { nome: "resistencias", tipo: "json" },
      { nome: "vulnerabilidades", tipo: "json" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "habitat", tipo: "textarea" },
      { nome: "comportamento", tipo: "textarea" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "sinal", tipo: "textarea" },
      { nome: "lore", tipo: "textarea" },
      { nome: "notas", tipo: "textarea", segredo: true },
      { nome: "drops", tipo: "json" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  armas: {
    pk: "id",
    rotulo: "Armas (itens)",
    icone: "⚔️",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "requisito", tipo: "text" },
      { nome: "preco", tipo: "number" },
      { nome: "preco_txt", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "efeito", tipo: "textarea" },
      { nome: "obter", tipo: "textarea" },
      { nome: "skills", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  equipamentos: {
    pk: "id",
    rotulo: "Equipamentos",
    icone: "🥋",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "slot", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "conjunto", tipo: "bool" },
      { nome: "arquivo", tipo: "text" },
      { nome: "requisito", tipo: "text" },
      { nome: "preco", tipo: "number" },
      { nome: "preco_txt", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "efeito", tipo: "textarea" },
      { nome: "obter", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  moves_arma: {
    pk: "nome",
    rotulo: "Golpes de Arma",
    icone: "🗡️",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "marca", tipo: "textarea" },
      { nome: "move_a", tipo: "json" },
      { nome: "move_b", tipo: "json" },
      { nome: "golpe_2", tipo: "json" },
      { nome: "golpe_3", tipo: "json" },
      { nome: "limit_breaker", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  moves_profissao: {
    pk: "nome",
    rotulo: "Golpes de Profissão",
    icone: "🛠️",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "marca", tipo: "textarea" },
      { nome: "move_a", tipo: "json" },
      { nome: "move_b", tipo: "json" },
      { nome: "move_c", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cartas: {
    pk: "id",
    rotulo: "Cartas (catálogo)",
    icone: "🃏",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "tipo_bonus", tipo: "text" },
      { nome: "valor_bonus", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "drop_de", tipo: "text" },
      { nome: "chance_drop", tipo: "number" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cristais: {
    pk: "id",
    rotulo: "Cristais (catálogo)",
    icone: "💎",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "tipo_bonus", tipo: "text" },
      { nome: "valor_bonus", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "drop_de", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },

  npcs: {
    pk: "id",
    rotulo: "NPCs",
    icone: "🧑",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "img", tipo: "text" },
      { nome: "papel", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "arma", tipo: "text" },
      { nome: "local", tipo: "text" },
      { nome: "atributos", tipo: "json" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "gancho", tipo: "textarea" },
      { nome: "falas", tipo: "json" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "canonico", tipo: "bool" },
      { nome: "fonte", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  quests: {
    pk: "id",
    rotulo: "Quests (narrativa)",
    icone: "📜",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "titulo", tipo: "text" },
      { nome: "cadeia", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "dificuldade", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "npc", tipo: "text" },
      { nome: "requer", tipo: "json" },
      { nome: "desbloqueia", tipo: "json" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cronicas: {
    pk: "id",
    rotulo: "Crônicas",
    icone: "📖",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "numero", tipo: "number" },
      { nome: "ep_rotulo", tipo: "text" },
      { nome: "titulo", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "dificuldade", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "conexoes", tipo: "text" },
      { nome: "elenco", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  guias: {
    pk: "id",
    rotulo: "Guias de Região",
    icone: "🗺️",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "bioma", tipo: "text" },
      { nome: "nivel", tipo: "text" },
      { nome: "chegada", tipo: "text" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "cena", tipo: "textarea" },
      { nome: "acoes", tipo: "json" },
      { nome: "mestre", tipo: "textarea", segredo: true },
      { nome: "demora", tipo: "textarea" },
      { nome: "evento", tipo: "textarea" },
      { nome: "locais", tipo: "json" },
      { nome: "ligado", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  puzzles: {
    pk: "id",
    rotulo: "Puzzles",
    icone: "🧩",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "n", tipo: "number" },
      { nome: "nome", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "cadeia", tipo: "text" },
      { nome: "duracao", tipo: "text" },
      { nome: "verdade", tipo: "textarea", segredo: true },
      { nome: "recompensa", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  dungeons: {
    pk: "id",
    rotulo: "Dungeons",
    icone: "🏰",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "nivel", tipo: "text" },
      { nome: "perfil", tipo: "textarea" },
      { nome: "nota", tipo: "textarea" },
      { nome: "setores", tipo: "json" },
      { nome: "salas", tipo: "json" },
      { nome: "ligacoes", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  salas_dungeon: {
    pk: "id",
    rotulo: "Salas de Dungeon",
    icone: "🚪",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "dungeon_id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  cidades: {
    pk: "id",
    rotulo: "Cidades",
    icone: "🏙️",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "andar", tipo: "text" },
      { nome: "tipo_de_zona", tipo: "text" },
      { nome: "guildas_presentes", tipo: "json" },
      { nome: "canonico", tipo: "bool" },
      { nome: "fonte", tipo: "text" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "arquivo", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  clas: {
    pk: "nome",
    rotulo: "Clãs",
    icone: "🛡️",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "destaque", tipo: "bool" },
      { nome: "forca", tipo: "text" },
      { nome: "necessidade", tipo: "text" },
      { nome: "rival", tipo: "text" },
      { nome: "rumor", tipo: "text" },
      { nome: "status", tipo: "text" },
      { nome: "resumo", tipo: "textarea" },
      { nome: "bons", tipo: "textarea" },
      { nome: "precisa", tipo: "textarea" },
      { nome: "nao_admitem", tipo: "textarea" },
      { nome: "proximo", tipo: "textarea" },
      { nome: "atravessado", tipo: "textarea" },
      { nome: "quests", tipo: "textarea" },
      { nome: "aparecem", tipo: "textarea" },
      { nome: "simbolo", tipo: "textarea" },
      { nome: "reputacao", tipo: "json" },
      { nome: "ganchos", tipo: "json", segredo: true },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  pontos: {
    pk: "id",
    rotulo: "Pontos do Mapa",
    icone: "📍",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "categoria", tipo: "text" },
      { nome: "x", tipo: "number" },
      { nome: "y", tipo: "number" },
      { nome: "tipo", tipo: "text" },
      { nome: "ref", tipo: "text" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "respawn_horas", tipo: "number" },
      { nome: "teste", tipo: "json" },
      { nome: "recompensa", tipo: "textarea" },
      { nome: "ameaca", tipo: "text" },
      { nome: "golpes", tipo: "text" },
      { nome: "atributo_fraqueza", tipo: "text" },
      { nome: "fala", tipo: "textarea" },
      { nome: "oferece", tipo: "text" },
      { nome: "vende", tipo: "text" },
      { nome: "obs", tipo: "textarea" },
      { nome: "mestre", tipo: "textarea", segredo: true },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  pontos_detalhe: {
    pk: "id",
    rotulo: "Pontos — Detalhe",
    icone: "📌",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "leitura", tipo: "textarea" },
      { nome: "oque", tipo: "textarea" },
      { nome: "acoes", tipo: "json" },
      { nome: "mestre", tipo: "textarea", segredo: true },
      { nome: "atalhos", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  sistema: {
    pk: "titulo",
    rotulo: "Regras (Sistema)",
    icone: "📘",
    campos: [
      { nome: "titulo", tipo: "text" },
      { nome: "corpo", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },

  oficios: {
    pk: "nome",
    rotulo: "Ofícios",
    icone: "🔨",
    campos: [
      { nome: "nome", tipo: "text" },
      { nome: "atributo", tipo: "text" },
      { nome: "arquivo", tipo: "text" },
      { nome: "marca", tipo: "textarea" },
      { nome: "acoes", tipo: "json" },
      { nome: "postos", tipo: "json" },
      { nome: "contato", tipo: "text" },
      { nome: "gancho", tipo: "textarea" },
      { nome: "renda", tipo: "text" },
      { nome: "item", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  producao: {
    pk: "profissao",
    rotulo: "Produção (crafting)",
    icone: "⚙️",
    campos: [
      { nome: "profissao", tipo: "text" },
      { nome: "moeda", tipo: "text" },
      { nome: "itens", tipo: "json" },
      { nome: "vale", tipo: "textarea" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  materiais_basicos: {
    pk: "id",
    rotulo: "Materiais de Craft",
    icone: "🌿",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "nivel_obtencao", tipo: "number" },
      { nome: "categoria", tipo: "text" },
      { nome: "peso_uso_esperado", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "fonte", tipo: "textarea" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  receitas: {
    pk: "id",
    rotulo: "Receitas de Craft",
    icone: "📜",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "nivel_receita", tipo: "number" },
      { nome: "tipo", tipo: "text" },
      { nome: "nome_resultado", tipo: "text" },
      { nome: "resultado_item_id", tipo: "text" },
      { nome: "resultado_raridade", tipo: "text" },
      { nome: "atributo_teste", tipo: "text" },
      { nome: "dificuldade_mod", tipo: "number" },
      { nome: "folego_custo", tipo: "number" },
      { nome: "xp_recompensa", tipo: "number" },
      { nome: "materiais", tipo: "json" },
      { nome: "efeitos", tipo: "json" },
      { nome: "receita_refino", tipo: "bool" },
      { nome: "receita_estagio", tipo: "number" },
      { nome: "receita_antecessora_id", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  ferramentas_oficio: {
    pk: "id",
    rotulo: "Ferramentas de Ofício",
    icone: "🧰",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "nivel_ferramenta", tipo: "number" },
      { nome: "bonus_acao", tipo: "number" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "receita", tipo: "json" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  ovos_catalogo: {
    pk: "id",
    rotulo: "Catálogo de Ovos (Pets)",
    icone: "🥚",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "especie", tipo: "text" },
      { nome: "monstro_id", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "nivel_min", tipo: "number" },
      { nome: "tempo_chocagem_horas", tipo: "number" },
      { nome: "incubadora_min", tipo: "number" },
      { nome: "efeitos_padrao", tipo: "json" },
      { nome: "como_obter", tipo: "textarea" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  nivel_profissao_xp: {
    pk: "nivel",
    rotulo: "Curva de XP de Profissão",
    icone: "📈",
    campos: [
      { nome: "nivel", tipo: "number" },
      { nome: "xp_necessario", tipo: "number" },
    ],
  },
  mercado: {
    pk: "id",
    rotulo: "Lojas do Mapa (NPC)",
    icone: "🏪",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "regiao", tipo: "text" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "desconto", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  mercado_itens: {
    pk: "id",
    rotulo: "Itens à venda (loja NPC)",
    icone: "🛒",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "mercado_id", tipo: "text" },
      { nome: "item", tipo: "text" },
      { nome: "col", tipo: "text" },
      { nome: "obs", tipo: "text" },
    ],
  },
  compra_materiais: {
    pk: "id",
    rotulo: "Compra de Materiais (NPC)",
    icone: "💰",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "material", tipo: "text" },
      { nome: "col", tipo: "text" },
      { nome: "quem", tipo: "text" },
      { nome: "visivel", tipo: "bool" },
    ],
  },

  missoes_quadro: {
    pk: "id",
    rotulo: "Missões (Quadro)",
    icone: "⚔️",
    campos: [
      { nome: "id", tipo: "text" },
      { nome: "titulo", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "regiao", tipo: "text" },
      { nome: "alvo", tipo: "text" },
      { nome: "alvo_qtd", tipo: "number" },
      { nome: "raridade", tipo: "text" },
      { nome: "custo_folego", tipo: "number" },
      { nome: "recompensa_xp", tipo: "number" },
      { nome: "recompensa_col_min", tipo: "number" },
      { nome: "recompensa_col_max", tipo: "number" },
      { nome: "drop_item_id", tipo: "text" },
      { nome: "drop_chance", tipo: "number" },
      { nome: "drop_tabela", tipo: "text" },
      { nome: "reputacao_cla_nome", tipo: "text" },
      { nome: "reputacao_delta", tipo: "number" },
      { nome: "penalidade_col_falha", tipo: "number" },
      { nome: "penalidade_folego_falha", tipo: "number" },
      { nome: "nivel_min", tipo: "number" },
      { nome: "requer_grupo", tipo: "bool" },
      { nome: "excluido", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },

  transacoes: {
    pk: "id",
    rotulo: "Transações (Col)",
    icone: "🧾",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "de_personagem", tipo: "text" },
      { nome: "para_personagem", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "valor", tipo: "number" },
      { nome: "item_id", tipo: "text" },
      { nome: "observacao", tipo: "text" },
    ],
  },
  vitrine: {
    pk: "id",
    rotulo: "Vitrine (Mercado Jogador)",
    icone: "🏷️",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "vendedor_nome", tipo: "text" },
      { nome: "inventario_id", tipo: "number" },
      { nome: "preco_col", tipo: "number" },
      { nome: "expira_em", tipo: "text" },
      { nome: "vendido", tipo: "bool" },
      { nome: "comprador_nome", tipo: "text" },
    ],
  },
  inventario: {
    pk: "id",
    rotulo: "Inventário / Stash",
    icone: "🎒",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "item_id", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "quantidade", tipo: "number" },
      { nome: "equipado", tipo: "bool" },
      { nome: "slot", tipo: "text" },
      { nome: "cristal_id", tipo: "text" },
      { nome: "origem", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
    ],
  },
  criaturas_domadas: {
    pk: "id",
    rotulo: "Pets / Criaturas Domadas",
    icone: "🐾",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "especie", tipo: "text" },
      { nome: "monstro_id", tipo: "text" },
      { nome: "nome_pet", tipo: "text" },
      { nome: "raridade", tipo: "text" },
      { nome: "status", tipo: "text" },
      { nome: "incubadora_nivel", tipo: "number" },
      { nome: "efeitos", tipo: "json" },
      { nome: "choca_em", tipo: "text" },
      { nome: "nascido_em", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
    ],
  },
  nivel_profissao: {
    pk: "personagem_nome",
    rotulo: "Nível de Profissão (jogador)",
    icone: "🎓",
    campos: [
      { nome: "personagem_nome", tipo: "text" },
      { nome: "profissao", tipo: "text" },
      { nome: "nivel", tipo: "number" },
      { nome: "xp", tipo: "number" },
      { nome: "ultima_acao", tipo: "text" },
    ],
  },
  reputacao_personagem: {
    pk: "personagem_nome",
    rotulo: "Reputação (universal)",
    icone: "🤝",
    campos: [
      { nome: "personagem_nome", tipo: "text" },
      { nome: "alvo_nome", tipo: "text" },
      { nome: "alvo_tipo", tipo: "text" },
      { nome: "nivel", tipo: "number" },
      { nome: "motivo", tipo: "text" },
    ],
  },
  bestiario_roster: {
    pk: "id",
    rotulo: "Bestiário — Roster (até andar 50)",
    icone: "📖",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "andar", tipo: "number" },
      { nome: "bioma", tipo: "text" },
      { nome: "categoria", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "emoji", tipo: "text" },
      { nome: "materiais", tipo: "json" },
      { nome: "cristais", tipo: "json" },
      { nome: "cartas", tipo: "json" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  combate_log: {
    pk: "id",
    rotulo: "Log de Combate (item 17)",
    icone: "⚔️",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "monstro_nome", tipo: "text" },
      { nome: "resultado", tipo: "text" },
      { nome: "vida_perdida", tipo: "number" },
      { nome: "xp_ganho", tipo: "number" },
      { nome: "col_ganho", tipo: "number" },
      { nome: "drop_item_id", tipo: "text" },
    ],
  },
  cla_inventario: {
    pk: "id",
    rotulo: "Baú de Clã (item 18B)",
    icone: "🧰",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "cla_nome", tipo: "text" },
      { nome: "nome", tipo: "text" },
      { nome: "tipo", tipo: "text" },
      { nome: "qtd", tipo: "number" },
      { nome: "liberado_para_membros", tipo: "bool" },
      { nome: "depositado_por", tipo: "text" },
      { nome: "excluido", tipo: "bool" },
    ],
  },
  cla_autoridade: {
    pk: "id",
    rotulo: "Cargos de Clã (item 18B)",
    icone: "👑",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "cla_nome", tipo: "text" },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "cargo", tipo: "text" },
    ],
  },
  metas_globais: {
    pk: "id",
    rotulo: "Metas Globais (item 18C)",
    icone: "🎯",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "titulo", tipo: "text" },
      { nome: "descricao", tipo: "textarea" },
      { nome: "meta_item", tipo: "text" },
      { nome: "meta_qtd", tipo: "number" },
      { nome: "progresso", tipo: "number" },
      { nome: "recompensa_col", tipo: "number" },
      { nome: "recompensa_xp", tipo: "number" },
      { nome: "recompensa_item", tipo: "text" },
      { nome: "recompensa_reputacao_alvo_nome", tipo: "text" },
      { nome: "recompensa_reputacao_valor", tipo: "number" },
      { nome: "finalizada", tipo: "bool" },
      { nome: "visivel", tipo: "bool" },
    ],
  },
  metas_doacoes: {
    pk: "id",
    rotulo: "Doações de Meta (item 18C)",
    icone: "📥",
    campos: [
      { nome: "id", tipo: "number", auto: true },
      { nome: "meta_id", tipo: "number" },
      { nome: "personagem_nome", tipo: "text" },
      { nome: "qtd_doada", tipo: "number" },
    ],
  },
};

/* Agrupamento pra sidebar do Compêndio. "avancado" fica escondido atrás de
   um "mostrar mais" — são tabelas técnicas/estado-ao-vivo que o mestre
   raramente precisa editar linha a linha (a maior parte já tem tela própria
   no painel: Jogadores cuida de personagens, Mercado cuida de vitrine). */
export const GRUPOS_COMPENDIO = [
  {
    k: "bestiario",
    lbl: "Bestiário & Combate",
    ico: "💀",
    tabelas: ["monstros", "armas", "equipamentos", "moves_arma", "moves_profissao", "cartas", "cristais", "bestiario_roster", "combate_log"],
  },
  {
    k: "mundo",
    lbl: "Mundo & Narrativa",
    ico: "🗺️",
    tabelas: ["npcs", "quests", "cronicas", "guias", "puzzles", "dungeons", "salas_dungeon", "cidades", "clas", "pontos", "pontos_detalhe", "sistema"],
  },
  {
    k: "missoes",
    lbl: "Missões",
    ico: "⚔️",
    tabelas: ["missoes_quadro"],
  },
  {
    k: "oficios",
    lbl: "Ofícios & Craft",
    ico: "🔨",
    tabelas: ["oficios", "producao", "materiais_basicos", "receitas", "ferramentas_oficio", "ovos_catalogo", "nivel_profissao_xp"],
  },
  {
    k: "comercio",
    lbl: "Comércio",
    ico: "🏪",
    tabelas: ["mercado", "mercado_itens", "compra_materiais"],
  },
  {
    k: "avancado",
    lbl: "Avançado · estado ao vivo",
    ico: "🧪",
    colapsavel: true,
    tabelas: ["transacoes", "vitrine", "inventario", "criaturas_domadas", "nivel_profissao", "reputacao_personagem",
      "cla_inventario", "cla_autoridade", "metas_globais", "metas_doacoes"],
  },
];
